### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by nikita-nikita-nikita** [nikita-nikita-nikita/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by study-bsa-20-colaborate** [comment]
― I wanna create cool website, that can be adaptive and usefull. I like programming, so I will create it by myself. I am my own customer.

**Comment by nikita-nikita-nikita** [comment]
TY! Good job.
