### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by nikita-nikita-nikita** [nikita-nikita-nikita/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by study-bsa-20-colaborate** [comment]
That ara ambitious person, who wanna learn how to make good websites with good design and fast speed using advanced technologies, for example react. Also GitHub will help me with this, it will host my websites and store my data regarding projects.

**Comment by nikita-nikita-nikita** [comment]
TY!
