### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by nikita-nikita-nikita** [nikita-nikita-nikita/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by study-bsa-20-colaborate** [comment]
https://instagram.com/nikita_good_guy?igshid=1qns9of8yyidn
https://tele.gg/STALINNASHPRESIDENT

**Comment by nikita-nikita-nikita** [comment]
Good job, mate
