### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by nikita-nikita-nikita** [nikita-nikita-nikita/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by study-bsa-20-colaborate** [comment]
## 2008
I went to school

## 2017
Started learning programming
 
## 2019 MAY
Passed External Peer Review (ЗНО - українською)

## 2019 AUGUST
Enterned the KPI

## 2020
Passed Binary Studio Academy test. 

## NOW
Hope, that I will pass the second stage!

**Comment by nikita-nikita-nikita** [comment]
WOW! Nice :)
