### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by nikita-nikita-nikita** [nikita-nikita-nikita/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by study-bsa-20-colaborate** [comment]
## LANGUAGES
🇺🇸 ENGLISH 🇷🇺 РУССКИЙ ua УКРАЇНСЬКА 

## SKILLS
Programming - JS, CSS, HTML, React, MongoDB, C++, C.

## CHARACTER
Purposeful, team player, I like to improve myself and cats.

## EDUCATION
Finished school. Studying at university.

## LIKES
Programming, Footbal, Big Mac, be the best, TV series.

## DISLIKES
Laziness, Procrastination, Vanity, Tomato juice.
